### ISSUE TITLE
elytra可以被戴在头上

### ISSUE THREAD

**Issue by immediately233** [B-2U/MCDR-Hat#4]
代码内有禁止特定的item戴在头上，但是elytra的id是要小写，否则是不起作用的
![~XKSZ39)L97}W}Q{JX2PN5M](https://user-images.githubusercontent.com/68837366/126283699-abf5050b-d3e7-44c6-a131-f24dad9451f5.png)

**Comment by immediately233** [comment]
鞘翅和已经被戴在头上的物品互换的话，会复制物品
![17O50(%17NC`}NPMYHSE A](https://user-images.githubusercontent.com/68837366/126285640-8c58fd53-9b96-4b01-8f1b-afe1a627f483.png)

**Comment by B-2U** [comment]
已修正
